- id: verible-verilog-format
  name: verible-verilog-format
  description: Test verilog files with verible-verilog-format
  entry: verible-verilog-format
  language: python
  types: [verilog, system-verilog]
- id: verible-verilog-lint
  name: verible-verilog-lint
  description: Test verilog files with verible-verilog-lint
  entry: verible-verilog-lint
  language: python
  types: [verilog, system-verilog]
